spring:
  application:
    name: Product
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/Product?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081